service: address

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-west-1
  memorySize: 128
  timeout: 10
  apiGateway:
    shouldStartNameWithService: true

package:
  exclude:
    - '**/*'
  include:
    - src/**

functions:
  hello:
    handler: src/index.handler
    events:
      - http:
          path: address
          method: get
